/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdotsoft_jarloader_test_NativeCode */

#ifndef _Included_com_jdotsoft_jarloader_test_NativeCode
#define _Included_com_jdotsoft_jarloader_test_NativeCode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdotsoft_jarloader_test_NativeCode
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jdotsoft_jarloader_test_NativeCode_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
